### ISSUE TITLE
Revise combine constraints in lazy discrete post

### ISSUE THREAD

**Issue by mforets** [JuliaReach/Reachability.jl#511] opened 2019-03-05 14:33 UTC
```julia
        if combine_constraints # combine the constraints of invariant and guard
            T = inv_isa_H_polytope || guard_isa_H_polytope ? HPolytope : HPolyhedron
            # TODO: remove redundant constraints => use intersection(..)
            invariant_guard = T([constraints_list(source_invariant);
                                 constraints_list(guard)])
        end
```

**Comment by schillic** [comment] 2019-03-05 21:39
Duplicate of #492.

**Closed by schillic** 2019-03-05 21:39 UTC
