### ISSUE TITLE
Systems package

### ISSUE THREAD

**Issue by blegat** [JuliaReach/Reachability.jl#31] opened 2017-11-28 14:45 UTC
I noticed that you have a [Systems module](https://github.com/JuliaReach/Reachability.jl/blob/master/src/Systems/Systems.jl) in the package.
I also started some generic system definition [in HybridSystems.jl](https://github.com/blegat/HybridSystems.jl/blob/master/src/systems.jl).

Would you be interested in create a `Systems.jl` package which defines an abstraction for systems that can be shared accross the Julia ecosystem ?
It will probably not depend on LazySet since this is specific to your package but we could for example replace
```julia
struct DiscreteSystem <: AbstractSystem
    # system's matrix
    A::Union{AbstractMatrix{Float64}, SparseMatrixExp{Float64}}
    # initial states
    X0::LazySet
end
```
with
```julia
struct DiscreteSystem{SetType} <: AbstractSystem
    # system's matrix
    A::Union{AbstractMatrix{Float64}, SparseMatrixExp{Float64}}
    # initial states
    X0::SetType
end
```

I already tried to motivate the creation of this package [here](https://github.com/JuliaDynamics/DynamicalSystems.jl/issues/23) but it didn't take off.

**Comment by blegat** [comment] 2017-11-28 18:28
It would be very nice to have a package for reachability analysis on Hybrid Systems, on [SwitchOnSafety](https://github.com/blegat/SwitchOnSafety.jl), I compute invariant sets using sum of squares programming only and I currently don't know any package that computes polyhedral invariant sets for hybrid systems.

I don't really know what would be the best definitions for the Systems.jl package but it should be not too far from what you have in this package and what I have in HybridSystems.jl. The tricky thing is to make it generic and flexible enough to meet everyone's need while being fast and type stable. With parametric types in Julia, it seems to be feasible. We can start discussing specific details once we have a stab.

**Comment by blegat** [comment] 2017-11-28 18:46
Looking at your code in `Systems` module, I am wondering: why isn't `SparseMatrixExp` an `AbstractMatrix` ?

**Comment by mforets** [comment] 2017-11-28 21:36
> Looking at your code in Systems module, I am wondering: why isn't SparseMatrixExp an AbstractMatrix ?

the problem is that one cannot guarantee fast access to single elements in the array, see [this comment](https://github.com/acroy/Expokit.jl/issues/9#issuecomment-335449065). whenever Expokit provides such lazy mat exp type, then yes, we should use it here too.

**Comment by mforets** [comment] 2017-11-29 06:24
Thanks for starting [Systems.jl](https://github.com/blegat/Systems.jl). I guess we can continue the discussion there, or on our gitter channel.

Some comments: (i) for travel reasons i won't be able to be active until a week or so; (ii) now or later would you be ok to transfer that repo to this organization? (we can discuss this further); (iii) in this package we've been including the initial states as part of the system definition. this choice is arguable and i'm ready to remove it; (iv) about the question "what are good definitions for systems", is not easy to make everyone happy, but one way is to choose some standard work and try to adjust the implementation for some solid concepts. there is discussion in [Chapter 2 of Sontag's Mathematical Control Theory](http://www.mit.edu/~esontag/FTPDIR/sontag_mathematical_control_theory_springer98.pdf); these definitions should be abstract enough for the applications that we have in mind, and then we can specialize for some particular classes of systems.

**Comment by mforets** [comment] 2017-11-29 09:21
Thanks, Systems.jl has been transferred to JuliaReach 👍 as i said, i cannot start working on it right now.. i'm moving all my real life repositories to another continent :)

**Comment by blegat** [comment] 2017-11-29 14:26
(i) No problem. I am submitting to ADHS for which the deadline is 8 of december so I don't have much time in the following two weeks either
(ii) I have transferred you the ownership. You can add it in JuliaReach. In the long term, I would imagine that Systems.jl and HybridSystems.jl should be in an organization like JuliaSystems which is not specific to reachability analysis but for now, JuliaReach seems to be the best place to put it at least for now :)
(iii) I think some implementation of system should include it.
(iv) It is difficult to find a description that will be efficient for every use case. There will always be someone complaining that he needs a more efficient representation for his use case. I would suggest to put an abstract interface that is agnostic to any representation and then create reasonable default implementation that satisfy most people. If this default implementation type is correctly parametrized, it can still cover many use cases.
The packages relying on Systems.jl wouldn't assume anything about the representation but it is possible that they are more efficient for some representation.

**Comment by schillic** [comment] 2017-12-29 17:12
@blegat @mforets: Should we close this one?

**Comment by mforets** [comment] 2017-12-29 18:28
Should we begin using Systems.jl as a dependency for this repo? What would be missing?

**Comment by schillic** [comment] 2017-12-29 18:37
> Should we begin using Systems.jl as a dependency for this repo? What would be missing?

Right, I just created #41 for this purpose.

**Closed** 2017-12-29 18:38 UTC
Labels: discussion
